### ISSUE TITLE
Account Balance

### ISSUE THREAD

**Issue by alexsicart** [AragonOne/issues#11]
Ethers doesn't appear in my MetaMask account. (Aragon app) In Google Chrome yes.

**Comment by izqui** [comment]
Can't replicate. Insufficient information for doing so.

**Comment by izqui** [comment]
Additional help: Are you using the same key? Inside the Aragon app, unless you have imported your seed, you have different accounts.

Metamask doesn't support Kovan on Chrome yet, so whatever you are seeing in Chrome it isn't kETH, unless using a public RPC Kovan provider.
