### ISSUE TITLE
Queue weird state when transaction confirms while popup is opened

### ISSUE THREAD

**Issue by izqui** [AragonOne/issues#14]
If I keep the popup opened, once the transaction is confirmed and removed, it stays on screen with 0 elements.

![2017-03-20 at 12 19 40 pm](https://cloud.githubusercontent.com/assets/447328/24097785/b55534e0-0d67-11e7-8a74-0b936abe7b65.png)
![2017-03-20 at 12 19 44 pm](https://cloud.githubusercontent.com/assets/447328/24097789/b739bf92-0d67-11e7-9769-6f55bd8e44ff.png)

**Comment by luisivan** [comment]
Solved!
