### ISSUE TITLE
Stock detail UI

### ISSUE THREAD

**Issue by izqui** [AragonOne/issues#20]
For this new release we need a simple way for people to check all stock classes and its properties.

My suggestion is: Main ownership view should show a top table with all stock classes and its total supplies (`Stocks.find()`), and below maybe the current shareholders view. 

When clicking on a stock should show main details: `name, symbol, votingPower, economicRights` and parent token in the case of wrappers. All properties are in the Stock object in minimongo.

Maybe a local chart for the stock class distribution would be helpful.

**Comment by izqui** [comment]
Now `parentToken` property also available on Stock storage objects. 

Working on prototype for entity ownership view for wrapping and unwrapping tokens.

**Comment by luisivan** [comment]
Solved
