### ISSUE TITLE
Bad UI for both Windows and Linux

### ISSUE THREAD

**Issue by shbour** [AragonOne/issues#43]
The UI for Ubuntu 16 is a bit broken as you can see on those pictures :

https://gyazo.com/7abbffcea9b86789f9d1ab3d0a580084
https://gyazo.com/a5d27d2ae42b866e86ffb359fe4b6fb9

**Comment by izqui** [comment]
Thanks for reporting, this was already solved by @luisivan (can't find the specific issue tho). 

If you download the version 0.3.0 now, it has been fixed :)
